### ISSUE TITLE
nifti_clib speed "issues"

### ISSUE THREAD

**Issue by i3roly** [neurolabusc/znzlib#1]
hi

i am trying to use nifti_read_collapsed_image to read the data in as timeseries.

whether i use an nii.gz file or not, it's still quite slow. this is in spite of me using threads to read the fMRI in "chunks". 

i am at a loss as to why this would be occurring. every other part of my code using my threading approach is very quick (intel MKL matrix computations in each of them, too).

nifti_image_read is being called with the second parameter as 'true', so before i call nifti_read_collapsed_image, the data should already be in memory ready to go.

it feels like there is some kind of blocking going on, or something. i have no idea why it's so slow. even if i use a single thread and call this function to read in the time series, it is no faster.

do you have any tips?

**Comment by i3roly** [comment]
definitely an issue with threading.

background: std::thread::hardware_concurrency()) is 24 for my machine.

trying to run 24*MULTIPLE where MULTIPLE >=12 will cause this issue when calling nifti_read_collapsed_image from the threads:

```
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
** no image file found for 'fakedir/adnisub/restw.nii.gz'
```

but if i dial it down to, say, MULTIPLE=10, it seems to work.

man, there has to be a better way to make this loading faster. MATLAB and others are so quick.

**Comment by neurolabusc** [comment]
@i3roly this is merely a fork of [nifti_clib](https://github.com/NIFTI-Imaging/nifti_clib) that enables high performance compression. I would direct issues their for specific details. You are clearly using this library very differently from me. In general, the gzip format is a poor choice for random access. In addition, I would except disk contention issues is you try to read a lot of threads simultaneously. CPUs are fast, but hard disks (an spinning hard disks in particular) have limited IO and strong expectations of sequential reading (either physically or for cache lines). If you look at niimath, you will see that I try to read datasets sequentially. I have never used the nifti_read_collapsed_image function of this library. If your use case demands non-sequential sampling of huge files, you may want to set up your own high performance solution. Historically, for existing tools I have even used RAM disks for improving access times.

**Comment by i3roly** [comment]
Hi Chris,

My apologies on asking here, as you're right this would be an issue for nifti clib's git.

I thought it was worth a shot asking here since you would be familiar with the library, and no doubt you're right that I am likely better off devising my own way to access the data.

On that note, I was going to ask if you have enough knowledge about how nifti clib operates. For example, if I call nifti_image_load with the second argument as true, does the nifti_image->data member (a double void pointer) hold all of the data (gzipped image or not) afterwards?

I was hoping maybe you had some knowledge on how I could access this data. I'll show a snippet of how I was trying to access it in a second here.

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Chris Rorden
Sent: Wednesday, 10 January 2024 1:34 AM
To: neurolabusc/znzlib
Reply To: neurolabusc/znzlib
Cc: gagan sidhu; Mention
Subject: Re: [neurolabusc/znzlib] nifti_clib speed "issues" (Issue #1)


@i3roly<https://github.com/i3roly> this is merely a fork of nifti_clib<https://github.com/NIFTI-Imaging/nifti_clib> that enables high performance compression. I would direct issues their for specific details. You are clearly using this library very differently from me. In general, the gzip format is a poor choice for random access. In addition, I would except disk contention issues is you try to read a lot of threads simultaneously. CPUs are fast, but hard disks (an spinning hard disks in particular) have limited IO and strong expectations of sequential reading (either physically or for cache lines). If you look at niimath, you will see that I try to read datasets sequentially. I have never used the nifti_read_collapsed_image function of this library. If your use case demands non-sequential sampling of huge files, you may want to set up your own high performance solution. Historically, for existing tools I have even used RAM disks for improving access times.

**Comment by neurolabusc** [comment]
Feel free to look at my usage for [niimath](https://github.com/rordenlab/niimath) where I use nifti_image_read() to load a data structure. You then have access to the raw uncompressed data in your nim->data pointer. You will want to [typecast](https://github.com/rordenlab/niimath/blob/b2c882bd371bc5352578b5e98ec3dc7c626c4345/src/core.c#L496) this for the correct nim->datatype:

```
double *f64 = (double *)nim->data;
float *f32 = (float *)nim->data;
uint64_t *u64 = (uint64_t *)nim->data;
int64_t *i64 = (int64_t *)nim->data;
uint32_t *u32 = (uint32_t *)nim->data;
int32_t *i32 = (int32_t *)nim->data;
uint16_t *u16 = (uint16_t *)nim->data;
int16_t *i16 = (int16_t *)nim->data;
uint8_t *u8 = (uint8_t *)nim->data;
int8_t *i8 = (int8_t *)nim->data;
```
Note that because the entire image is loaded into RAM, you have easy and fast access, but this will demand a lot of RAM for large images.

**Comment by i3roly** [comment]
hi chris, 

thanks for that info. i have tried something similar, but i don't think it's right in terms of copying the members

```
nifti_image_ptr = nifti_image_read(fpath, true);

int volSize = nifti_image->nx*nifti_image->ny*nifti_image->nz;

// assuming we want to copy the t-dim time series of index 'ind'
for (int t=0; t<nifti_image->nt; t++)
	memcpy(&twoDshortArray[ind][t],(nifti_image->data + sizeof(int16_t)*volSize + ind),sizeof(int16_t));
```

i could cast it, as above, where i tried this:

```
int16_t *dataPtr = (int16_t *) nifti_image->data;
int volSize = nifti_image->nx*nifti_image->ny*nifti_image->nz;
// assuming we want to copy the t-dim time series of index 'ind'
for (int t=0; t<nifti_image->nt; t++)
	memcpy(&twoDshortArray[ind][t],&(dataPtr[t*volSize + ind]),sizeof(int16_t));
```
but it seems

**Comment by i3roly** [comment]
nevermind sir, it seems like either of the approaches work and it's something else now (lol).

thank you!!

**Comment by i3roly** [comment]
a side note chris: you got any good recommendations for me to post all of this ABIDE/ADHD200/COBRE/etc (pretty much like, at least, 50% of the NITRC public data that had subjects and patients) publicly?

i already have it on an [ieee dataport](https://ieee-dataport.org/documents/locally-linear-embedding-and-fmri-feature-selection-psychiatric-classification), but all of the reconstructed images are packed inside a mat file for each subject (lol).

recent events motivated me to write all of these 4d reconstructions to their own nifti files, and i suspect others may appreciate this since people probably use nasty python (lol, i hate the double parentheses and printout of lists of lists lol sorry) and might not want to spend the effort to unpack them from the mat files.

it's crazy how many corporate overlords there are in "the field", but at the same time i shouldn't be too surprised by this.

i think "it's time" for people to go wild with these images. i still recommend a fresh way to approach the reconstructed images, but hey people are gonna do what they do.

i don't know how i wanna go about this either haha since i have posted the versions with the mat file already. do i include the mat file in this one, even though i have all of the relevant images in nifti? i want to do this, but it would add 175mbish to each subject.

maybe you don't care. thought i'd ask since you were so helpful.

**Comment by neurolabusc** [comment]
@i3roly this question is outside my expertise and out of scope for this repository. Off the top of my head, it seems you will want to publish the methods you use to create this derived data and create a Github page for replicating your processing. Providing the derived data on ieee dataport seems appropriate (as the source data uses CC license). Scipy can read mat files, so I would not change the data you distribute if it is the product of your processing pipeline. [neurostars](https://neurostars.org/) would be a great venue to get advice and develop a consensus.

**Comment by i3roly** [comment]
Already published and all of the intermediates and raw/processed data are available.

Lol how haven't you heard of it by now?! But yes that is off topic you are correct.

I remember our dcm2nii conversations fondly, still :)

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Chris Rorden
Sent: Saturday, 13 January 2024 6:38 AM
To: neurolabusc/znzlib
Reply To: neurolabusc/znzlib
Cc: gagan sidhu; Mention
Subject: Re: [neurolabusc/znzlib] nifti_clib speed "issues" (Issue #1)


@i3roly<https://github.com/i3roly> this question is outside my expertise and out of scope for this repository. Off the top of my head, it seems you will want to publish the methods you use to create this derived data and create a Github page for replicating your processing. Providing the derived data on ieee dataport seems appropriate (as the source data uses CC license). Scipy can read mat files, so I would not change the data you distribute if it is the product of your processing pipeline. neurostars<https://neurostars.org/> would be a great venue to get advice and develop a consensus.
